spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI}
      database: ${SPRING_MONGODB_BASE_NAME}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}
  cookie-name: ${JWT_COOKIE_NAME}

aws:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket-name: ${S3_BUCKET_NAME}

frontend:
  url:
    dev: ${FRONTEND_URL_DEV}
backend:
  url:
    dev: ${BACKEND_URL_DEV}



