spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${SPRING_APPLICATION_NAME}
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI}
      database: ${SPRING_MONGODB_BASE_NAME}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}
